apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configmap" .Release.Name | trunc 63 | trimSuffix "-" }}
data:
  server.toml: |
    rust_log = "sqlx=debug,tower_http=info,cim_slo=error,cim_storage=debug,cim_pim=debug,cim_server=debug,server=debug"
    cors_origin = "127.0.0.1"
    database_url = "mysql://root:1234567@172.28.92.71:3306/cim?charset=utf8mb4&parseTime=true&loc=UTC"
    run_migrations = true
