apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" .Release.Name | trunc 63 | trimSuffix "-" }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
