[workspace]
resolver = "2"
members = [
    "server",
    "client",
    "pim",
    "examples/pim_demo",
    "connect",
    "storage",
    "slo",
]
default-members = ["server"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
askama = { version = "0.12" }
jsonwebkey = { version = "0.3", features = ["generate", "jwt-convert"] }
dotenv = "0.15"
clap = { version = "4.4", features = ["derive", "env"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = { version = "1.0", features = ["backtrace"] }
serde_json = { version = "1.0", features = ["raw_value"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
validator = { version = "0.16", features = ["derive"] }
regex = "1.10"
mockall = "0.12"
async-trait = "0.1"
axum = { version = "0.7.4", features = ["tracing"] }
