[package]
name = "cim-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = true

[[bin]]
name = "server"
path = "src/bin/main.rs"

[dependencies]
cim-core = { path = "../core" }

tokio = { version = "1.24", features = ["full"] }
axum = { version = "0.6", features = ["headers"] }
async-trait = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
http = "0.2"
validator = { version = "0.16", features = ["derive"] }
anyhow = { version = "1.0", features = ["backtrace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.4", features = ["trace", "cors", "fs"] }
uuid = { version = "1.2", features = ["v4"] }
metrics = "0.21"
metrics-exporter-prometheus = "0.12"
prometheus = { version = "=0.13.3", default-features = false }
lazy_static = "1.4"
dotenv = "0.15"
clap = { version = "4.4", features = ["derive", "env"] }
sqlx = { version = "0.6", features = [
    "mysql",
    "runtime-tokio-rustls",
    "chrono",
    "offline"
] }
regex = "1.7"
serde_urlencoded = "0.7"
chrono = { version = "0.4", features = ["serde"] }
lru = "0.11"
cidr-utils = "0.5"
mockall = "0.11"
rust-argon2 = "2.0"
rand = "0.8"
askama = "0.12"
oauth2 = "4.3"
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls",
    "json",
] }
base64 = "0.21"
jsonwebtoken = "8.2"
sha2 = "0.10"

mimalloc = { version = "0.1.30", default-features = false, optional = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.5.0", package = "tikv-jemallocator", optional = true }

[features]
default=["mimalloc"]
jemalloc = ["jemallocator"]
