[package]
name = "pim_demo"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pim = { path = "../../pim" }
serde_json = { workspace = true }
anyhow = { workspace = true }
