[package]
name = "cim-client"
edition.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cimctl"
path = "src/bin/main.rs"

[dependencies]
clap = { workspace = true }
